version: '3.8'
services:
  api:
    container_name: backend
    stdin_open: true
    tty: true
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend
    networks:
      - frontend_backend
    volumes:
      - ./backend:/app
    ports:
      - "8005:8005"
    command: ./manage.py runserver 0.0.0.0:8005
    environment:
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - LOGIN_URL=http://localhost:8005/logged_in
      - FRONTEND_URL=http://localhost:5005
  react:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    user: $WEB_UID:$WEB_GID
    image: frontend
    networks:
      - frontend_backend
    volumes:
      - ./frontend/technical:/app
    ports:
      - "5005:5005"
    command: npm run dockerDevStart
    environment:
      - REACT_APP_BACKEND_ROUTE=http://localhost:8005
networks:
  frontend_backend:
    name: frontend_backend
    driver: bridge